import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { Providers } from '@/providers'
import { ToastContainer } from 'react-toastify'
import Sidebar from '@/components/Sidebar'
import Header from '@/Layouts/Header'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Dashboard CMS',
  description: 'Generated by create next app'
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <ToastContainer />
        <Providers>
          <div className='flex min-h-dvh '>
            <div className='flex h-dvh w-[20%] flex-col gap-10 bg-[#fbfbfd] py-5'>
              <Link href='/' className='px-5 text-3xl font-bold'>
                CMS
              </Link>
              <Sidebar />
            </div>
            <div className='h-dvh w-[80%] overflow-auto'>
              <Header />
              {children}
            </div>
          </div>
        </Providers>
      </body>
    </html>
  )
}
